### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by JL2210** [tempesta-tech/blog#9]
Can you add license text to some of the examples? Currently, it's unclear as to what their licenses are.

**Comment by krizhanovsky** [comment]
Hi @JL2210 ,

thank you for the report. Yeah, there was some mess with the licensing. Fixed now. The code is published under GPLv2. However, please also note that there us borrowed code from other projects (Nginx, PostgreSQL, libdivide) and the code (now) has explicit statements that it's distributed under original project license. There are also references to the original projects.

**Comment by JL2210** [comment]
Oh, sorry, Just realized that it's only the benchmark that's included here. Thanks!
